CREATE TABLE `SEQUENCE` (
  `SEQ_NAME` varchar(50) NOT NULL,
  `SEQ_COUNT` decimal(38,0) DEFAULT NULL,
  PRIMARY KEY (`SEQ_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ;
CREATE TABLE `USERGRID_APPLICATION_PROPERTIES` (
  `ID` bigint(20) NOT NULL,
  `APPLICATION_NAME` varchar(500) NOT NULL,
  `APPLICATION_USER_COUNT` bigint(20) NOT NULL,
  `APPLICATION_UUID` varchar(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `APPLICATION_UUID` (`APPLICATION_UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ;
CREATE TABLE `USERGRID_COUNTERS` (
  `ID` bigint(20) NOT NULL,
  `COUNTER_VALIUE` bigint(20) NOT NULL,
  `COUNTER_NAME` varchar(500) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `COUNTER_NAME` (`COUNTER_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ;